version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: dinego_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678 # Thay bằng mật khẩu của bạn
      POSTGRES_DB: DineGoDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
