// <auto-generated />
using System;
using DineGo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DIneGo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DineGo.Models.BanAn", b =>
                {
                    b.Property<string>("SoBan")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("integer");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LoaiBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SucChua")
                        .HasColumnType("integer");

                    b.HasKey("SoBan");

                    b.ToTable("BanAn", (string)null);
                });

            modelBuilder.Entity("DineGo.Models.ChiTietPhieuNhapThucPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaThucPham")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("SoLuong")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SoPhieuNhap")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaThucPham");

                    b.HasIndex("SoPhieuNhap");

                    b.ToTable("ChiTietPhieuNhapThucPham", (string)null);
                });

            modelBuilder.Entity("DineGo.Models.ChiTietPhieuYeuCau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DonGiaDat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<Guid>("SoPhieuYeuCau")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaMon");

                    b.HasIndex("SoPhieuYeuCau");

                    b.ToTable("ChiTietPhieuYeuCau", (string)null);
                });

            modelBuilder.Entity("DineGo.Models.KhachHang", b =>
                {
                    b.Property<Guid>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("DineGo.Models.MonAn", b =>
                {
                    b.Property<string>("MaMon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DVT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MaNhom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("MaMon");

                    b.HasIndex("MaNhom");

                    b.ToTable("MonAn", (string)null);
                });

            modelBuilder.Entity("DineGo.Models.NhaCungCap", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("DineGo.Models.NhanVien", b =>
                {
                    b.Property<Guid>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HoTenNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaNV");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("DineGo.Models.NhomMonAn", b =>
                {
                    b.Property<string>("MaNhom")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaNhom");

                    b.ToTable("NhomMonAn", (string)null);
                });

            modelBuilder.Entity("DineGo.Models.PhieuNhapThucPham", b =>
                {
                    b.Property<Guid>("SoPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("MaNV")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("SoPhieuNhap");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.ToTable("PhieuNhapThucPham", (string)null);
                });

            modelBuilder.Entity("DineGo.Models.PhieuThanhToan", b =>
                {
                    b.Property<Guid>("SoPhieuThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DaThanhToan")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaNV")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SoPhieuYeuCau")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SoPhieuThanhToan");

                    b.HasIndex("MaNV");

                    b.HasIndex("SoPhieuYeuCau")
                        .IsUnique()
                        .HasDatabaseName("IX_PhieuThanhToan_SoPhieuYeuCau_Unique");

                    b.ToTable("PhieuThanhToan", (string)null);
                });

            modelBuilder.Entity("DineGo.Models.PhieuYeuCau", b =>
                {
                    b.Property<Guid>("SoPhieuYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<TimeSpan>("GioDat")
                        .HasColumnType("interval");

                    b.Property<Guid>("MaKH")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("NgayYeuCau")
                        .HasColumnType("date");

                    b.Property<string>("SoBan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("SoPhieuYeuCau");

                    b.HasIndex("MaKH");

                    b.HasIndex("SoBan", "NgayYeuCau", "GioDat")
                        .IsUnique()
                        .HasDatabaseName("IX_PhieuYeuCau_SoBan_NgayYeuCau_GioDat_NotCancelled")
                        .HasFilter("\"TrangThai\" != 4");

                    b.ToTable("PhieuYeuCau", (string)null);
                });

            modelBuilder.Entity("DineGo.Models.ThucPham", b =>
                {
                    b.Property<string>("MaThucPham")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DVT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenThucPham")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<double>("TonKhoHienTai")
                        .HasColumnType("double precision");

                    b.HasKey("MaThucPham");

                    b.ToTable("ThucPham", (string)null);
                });

            modelBuilder.Entity("DineGo.Models.ChiTietPhieuNhapThucPham", b =>
                {
                    b.HasOne("DineGo.Models.ThucPham", "ThucPham")
                        .WithMany("ChiTietPhieuNhapThucPhams")
                        .HasForeignKey("MaThucPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineGo.Models.PhieuNhapThucPham", "PhieuNhapThucPham")
                        .WithMany("ChiTietPhieuNhapThucPhams")
                        .HasForeignKey("SoPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhapThucPham");

                    b.Navigation("ThucPham");
                });

            modelBuilder.Entity("DineGo.Models.ChiTietPhieuYeuCau", b =>
                {
                    b.HasOne("DineGo.Models.MonAn", "MonAn")
                        .WithMany("ChiTietPhieuYeuCaus")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineGo.Models.PhieuYeuCau", "PhieuYeuCau")
                        .WithMany("ChiTietPhieuYeuCaus")
                        .HasForeignKey("SoPhieuYeuCau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonAn");

                    b.Navigation("PhieuYeuCau");
                });

            modelBuilder.Entity("DineGo.Models.MonAn", b =>
                {
                    b.HasOne("DineGo.Models.NhomMonAn", "NhomMonAn")
                        .WithMany("MonAns")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhomMonAn");
                });

            modelBuilder.Entity("DineGo.Models.PhieuNhapThucPham", b =>
                {
                    b.HasOne("DineGo.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhapThucPhams")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineGo.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuNhapThucPhams")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DineGo.Models.PhieuThanhToan", b =>
                {
                    b.HasOne("DineGo.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuThanhToans")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineGo.Models.PhieuYeuCau", "PhieuYeuCau")
                        .WithOne("PhieuThanhToan")
                        .HasForeignKey("DineGo.Models.PhieuThanhToan", "SoPhieuYeuCau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("PhieuYeuCau");
                });

            modelBuilder.Entity("DineGo.Models.PhieuYeuCau", b =>
                {
                    b.HasOne("DineGo.Models.KhachHang", "KhachHang")
                        .WithMany("PhieuYeuCaus")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineGo.Models.BanAn", "BanAn")
                        .WithMany("PhieuYeuCaus")
                        .HasForeignKey("SoBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BanAn");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DineGo.Models.BanAn", b =>
                {
                    b.Navigation("PhieuYeuCaus");
                });

            modelBuilder.Entity("DineGo.Models.KhachHang", b =>
                {
                    b.Navigation("PhieuYeuCaus");
                });

            modelBuilder.Entity("DineGo.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietPhieuYeuCaus");
                });

            modelBuilder.Entity("DineGo.Models.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhapThucPhams");
                });

            modelBuilder.Entity("DineGo.Models.NhanVien", b =>
                {
                    b.Navigation("PhieuNhapThucPhams");

                    b.Navigation("PhieuThanhToans");
                });

            modelBuilder.Entity("DineGo.Models.NhomMonAn", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("DineGo.Models.PhieuNhapThucPham", b =>
                {
                    b.Navigation("ChiTietPhieuNhapThucPhams");
                });

            modelBuilder.Entity("DineGo.Models.PhieuYeuCau", b =>
                {
                    b.Navigation("ChiTietPhieuYeuCaus");

                    b.Navigation("PhieuThanhToan");
                });

            modelBuilder.Entity("DineGo.Models.ThucPham", b =>
                {
                    b.Navigation("ChiTietPhieuNhapThucPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
